ТЗ 14 Add bookings
IvanRosokhach/java-shareit pull request #2
Opened 2023-05-05 14:15 UTC by IvanRosokhach

2023-05-05 16:22 UTC, db-exp requested changes

2023-05-05 16:22 UTC, db-exp commented on pom.xml
> +<!--			<version>2.7.0</version>-->
давай удалим

2023-05-05 16:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.debug("{} create", this.getClass().getName());
Лучше не писать везде this.getClass().getName() - в лог и так попадет имя класса, который пишет в лог

2023-05-05 16:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
не хватает аннотации Repository

2023-05-05 16:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking booking = bookingRepository.findById(bookingId)
bookingRepository.findById(bookingId)
                .orElseThrow(() -> new NotFoundException(String.format(NOT_FOUND_BOOKING, bookingId))); можно вынести в репозиторий 
Для Item тоже самое и для User

2023-05-05 16:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +public interface CommentRepository extends JpaRepository<Comment, Long> {
не хватает аннотации Repository

2023-05-05 16:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +public interface ItemRepository extends JpaRepository<Item, Long> {
не хватает аннотации Repository

2023-05-05 16:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
не хватает аннотации Repository

2023-05-07 14:40 UTC, IvanRosokhach commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking booking = bookingRepository.findById(bookingId)
На сегодняшний день так и не понял как это должно выглядеть.  Остальное исправил.

2023-05-08 07:34 UTC, db-exp approved these changes

2023-05-10 17:40 UTC, merged